package Prototypical;
// Generated 27 Feb, 2015 4:15:24 PM by Hibernate Tools 3.6.0



/**
 * AcdemicdetailsId generated by hbm2java
 */
public class AcdemicdetailsId  implements java.io.Serializable {


     private int desiredid;
     private String degreetype;
     private String institutionname;
     private int yearofpassing;
     private float percentageobtained;

    public AcdemicdetailsId() {
    }

    public AcdemicdetailsId(int desiredid, String degreetype, String institutionname, int yearofpassing, float percentageobtained) {
       this.desiredid = desiredid;
       this.degreetype = degreetype;
       this.institutionname = institutionname;
       this.yearofpassing = yearofpassing;
       this.percentageobtained = percentageobtained;
    }
   
    public int getDesiredid() {
        return this.desiredid;
    }
    
    public void setDesiredid(int desiredid) {
        this.desiredid = desiredid;
    }
    public String getDegreetype() {
        return this.degreetype;
    }
    
    public void setDegreetype(String degreetype) {
        this.degreetype = degreetype;
    }
    public String getInstitutionname() {
        return this.institutionname;
    }
    
    public void setInstitutionname(String institutionname) {
        this.institutionname = institutionname;
    }
    public int getYearofpassing() {
        return this.yearofpassing;
    }
    
    public void setYearofpassing(int yearofpassing) {
        this.yearofpassing = yearofpassing;
    }
    public float getPercentageobtained() {
        return this.percentageobtained;
    }
    
    public void setPercentageobtained(float percentageobtained) {
        this.percentageobtained = percentageobtained;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AcdemicdetailsId) ) return false;
		 AcdemicdetailsId castOther = ( AcdemicdetailsId ) other; 
         
		 return (this.getDesiredid()==castOther.getDesiredid())
 && ( (this.getDegreetype()==castOther.getDegreetype()) || ( this.getDegreetype()!=null && castOther.getDegreetype()!=null && this.getDegreetype().equals(castOther.getDegreetype()) ) )
 && ( (this.getInstitutionname()==castOther.getInstitutionname()) || ( this.getInstitutionname()!=null && castOther.getInstitutionname()!=null && this.getInstitutionname().equals(castOther.getInstitutionname()) ) )
 && (this.getYearofpassing()==castOther.getYearofpassing())
 && (this.getPercentageobtained()==castOther.getPercentageobtained());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getDesiredid();
         result = 37 * result + ( getDegreetype() == null ? 0 : this.getDegreetype().hashCode() );
         result = 37 * result + ( getInstitutionname() == null ? 0 : this.getInstitutionname().hashCode() );
         result = 37 * result + this.getYearofpassing();
         result = 37 * result + (int) this.getPercentageobtained();
         return result;
   }   


}


