package Prototypical;
// Generated 27 Feb, 2015 4:15:24 PM by Hibernate Tools 3.6.0



/**
 * Acdemicdetails generated by hbm2java
 */
public class Acdemicdetails  implements java.io.Serializable {


     private AcdemicdetailsId id;

    public Acdemicdetails() {
    }

    public Acdemicdetails(AcdemicdetailsId id) {
       this.id = id;
    }
   
    public AcdemicdetailsId getId() {
        return this.id;
    }
    
    public void setId(AcdemicdetailsId id) {
        this.id = id;
    }




}


