package Prototypical;
// Generated 1 Feb, 2015 4:12:43 PM by Hibernate Tools 3.6.0



/**
 * ContactPerson generated by hbm2java
 */
public class ContactPerson  implements java.io.Serializable {


     private Integer personid;
     private Long contactno;

    public ContactPerson() {
    }

	
    public ContactPerson(Integer personid) {
        this.personid = personid;
    }
    public ContactPerson(Integer personid, Long contactno) {
       this.personid = personid;
       this.contactno = contactno;
    }
   
    public Integer getPersonid() {
        return this.personid;
    }
    
    public void setPersonid(Integer personid) {
        this.personid = personid;
    }
    public Long getContactno() {
        return this.contactno;
    }
    
    public void setContactno(Long contactno) {
        this.contactno = contactno;
    }




}


