package Prototypical;
// Generated 1 Feb, 2015 4:12:43 PM by Hibernate Tools 3.6.0



/**
 * Desiredskills generated by hbm2java
 */
public class Desiredskills  implements java.io.Serializable {


     private DesiredskillsId id;
     private Jobopeningdetails jobopeningdetails;

    public Desiredskills() {
    }

    public Desiredskills(DesiredskillsId id, Jobopeningdetails jobopeningdetails) {
       this.id = id;
       this.jobopeningdetails = jobopeningdetails;
    }
   
    public DesiredskillsId getId() {
        return this.id;
    }
    
    public void setId(DesiredskillsId id) {
        this.id = id;
    }
    public Jobopeningdetails getJobopeningdetails() {
        return this.jobopeningdetails;
    }
    
    public void setJobopeningdetails(Jobopeningdetails jobopeningdetails) {
        this.jobopeningdetails = jobopeningdetails;
    }




}


