package Prototypical;
// Generated 1 Feb, 2015 4:12:43 PM by Hibernate Tools 3.6.0



/**
 * DesiredskillsId generated by hbm2java
 */
public class DesiredskillsId  implements java.io.Serializable {


     private int jobReferenceCode;
     private String desiredSkills;

    public DesiredskillsId() {
    }

    public DesiredskillsId(int jobReferenceCode, String desiredSkills) {
       this.jobReferenceCode = jobReferenceCode;
       this.desiredSkills = desiredSkills;
    }
   
    public int getJobReferenceCode() {
        return this.jobReferenceCode;
    }
    
    public void setJobReferenceCode(int jobReferenceCode) {
        this.jobReferenceCode = jobReferenceCode;
    }
    public String getDesiredSkills() {
        return this.desiredSkills;
    }
    
    public void setDesiredSkills(String desiredSkills) {
        this.desiredSkills = desiredSkills;
    }




}


