package Prototypical;
// Generated 1 Feb, 2015 4:12:43 PM by Hibernate Tools 3.6.0

import java.util.Set;





/**
 * Head generated by hbm2java
 */
public class Head extends Prototypical.Person implements java.io.Serializable {


     private String headDetail;
     private String headType;
     private byte[] headimg;
     private String imagename;

    public String getImagename() {
        return imagename;
    }

    public void setImagename(String imagename) {
        this.imagename = imagename;
    }

    public byte[] getHeadimg() {
        return headimg;
    }

    public void setHeadimg(byte[] headimg) {
        this.headimg = headimg;
    }
     
     

    
     
     

    public Head() {
    }

	
    public Head(Integer personid) {
        super(personid);        
    }
    public Head(Integer personid, String fname, String mname, String lname, String emailid, String street, String city, String state, String country, Integer pincode, String username, String password, String confirmpassword, Set contact, String headDetail, String headType,byte[] headimg,String imagename) {
        super(personid, fname, mname, lname, emailid, street, city, state, country, pincode, username, password, confirmpassword, contact);        
       this.headDetail = headDetail;
       this.headType = headType;
       this.headimg=headimg;
       this.imagename=imagename;
    }
   
    public String getHeadDetail() {
        return this.headDetail;
    }
    
    public void setHeadDetail(String headDetail) {
        this.headDetail = headDetail;
    }
    public String getHeadType() {
        return this.headType;
    }
    
    public void setHeadType(String headType) {
        this.headType = headType;
    }




}


