package Prototypical;
// Generated 1 Feb, 2015 4:12:43 PM by Hibernate Tools 3.6.0


import java.util.Set;

/**
 * Interviewee generated by hbm2java
 */
public class Interviewee extends Prototypical.Person implements java.io.Serializable {


     private String gender;
     private String nationality;
     private String marritalstatus;
     private String hobbies;
     private String dob;
     public String JRC;
     
    public Interviewee() {
    }

	
    public Interviewee(Integer personid) {
        super(personid);        
    }
    

    public Interviewee(String gender, String nationality, String marritalstatus, String hobbies, String dob) {
        this.gender = gender;
        this.nationality = nationality;
        this.marritalstatus = marritalstatus;
        this.hobbies = hobbies;
        this.dob = dob;
    }

    

    public Interviewee(String gender, String nationality, String marritalstatus, String hobbies, String dob, Integer personid, String fname, String mname, String lname, String emailid, String street, String city, String state, String country, Integer pincode, String username, String password, String confirmpassword, Set contact, Set langknown) {
        super(personid, fname, mname, lname, emailid, street, city, state, country, pincode, username, password, confirmpassword, contact);
        this.gender = gender;
        this.nationality = nationality;
        this.marritalstatus = marritalstatus;
        this.hobbies = hobbies;
        this.dob = dob;
    }
    
    
   
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getNationality() {
        return this.nationality;
    }
    
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }
    public String getMarritalstatus() {
        return this.marritalstatus;
    }
    
    public void setMarritalstatus(String marritalstatus) {
        this.marritalstatus = marritalstatus;
    }
    public String getHobbies() {
        return this.hobbies;
    }
    
    public void setHobbies(String hobbies) {
        this.hobbies = hobbies;
    }
    public String getDob() {
        return this.dob;
    }
    
    public void setDob(String dob) {
        this.dob = dob;
    }

    public String getJRC() {
        return JRC;
    }

    public void setJRC(String JRC) {
        this.JRC = JRC;
    }

   
}


