package Prototypical;
// Generated 1 Feb, 2015 4:12:43 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Jobopeningdetails generated by hbm2java
 */
public class Jobopeningdetails  implements java.io.Serializable {


     private int jobReferenceCode;
     private String department;
     private String gender;
     private String posting;
     private String vacancies;
     private String street;
     private String city;
     private String state;
     private String country;
     private String pincode;
     private float ctc;
     private String jobType;
     private Set requiedqualifications = new HashSet(0);
     private Set desiredskillses = new HashSet(0);
     private Set requireddocuments = new HashSet(0);

    public Jobopeningdetails() {
    }

	
    public Jobopeningdetails(int jobReferenceCode, String department, String gender, String posting, String vacancies, String street, String city, String state, String country, String pincode, float ctc, String jobType) {
        this.jobReferenceCode = jobReferenceCode;
        this.department = department;
        this.gender = gender;
        this.posting = posting;
        this.vacancies = vacancies;
        this.street = street;
        this.city = city;
        this.state = state;
        this.country = country;
        this.pincode = pincode;
        this.ctc = ctc;
        this.jobType = jobType;
    }
    public Jobopeningdetails(int jobReferenceCode, String department, String gender, String posting, String vacancies, String street, String city, String state, String country, String pincode, float ctc, String jobType, Set requiedqualifications, Set desiredskillses, Set requireddocuments) {
       this.jobReferenceCode = jobReferenceCode;
       this.department = department;
       this.gender = gender;
       this.posting = posting;
       this.vacancies = vacancies;
       this.street = street;
       this.city = city;
       this.state = state;
       this.country = country;
       this.pincode = pincode;
       this.ctc = ctc;
       this.jobType = jobType;
       this.requiedqualifications = requiedqualifications;
       this.desiredskillses = desiredskillses;
       this.requireddocuments = requireddocuments;
    }
   
    public int getJobReferenceCode() {
        return this.jobReferenceCode;
    }
    
    public void setJobReferenceCode(int jobReferenceCode) {
        this.jobReferenceCode = jobReferenceCode;
    }
    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getPosting() {
        return this.posting;
    }
    
    public void setPosting(String posting) {
        this.posting = posting;
    }
    public String getVacancies() {
        return this.vacancies;
    }
    
    public void setVacancies(String vacancies) {
        this.vacancies = vacancies;
    }
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getPincode() {
        return this.pincode;
    }
    
    public void setPincode(String pincode) {
        this.pincode = pincode;
    }
    public float getCtc() {
        return this.ctc;
    }
    
    public void setCtc(float ctc) {
        this.ctc = ctc;
    }
    public String getJobType() {
        return this.jobType;
    }
    
    public void setJobType(String jobType) {
        this.jobType = jobType;
    }
    public Set getRequiedqualifications() {
        return this.requiedqualifications;
    }
    
    public void setRequiedqualifications(Set requiedqualifications) {
        this.requiedqualifications = requiedqualifications;
    }
    public Set getDesiredskillses() {
        return this.desiredskillses;
    }
    
    public void setDesiredskillses(Set desiredskillses) {
        this.desiredskillses = desiredskillses;
    }
    public Set getRequireddocuments() {
        return this.requireddocuments;
    }
    
    public void setRequireddocuments(Set requireddocuments) {
        this.requireddocuments = requireddocuments;
    }




}


