package Prototypical;
// Generated 1 Feb, 2015 11:53:00 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Organization generated by hbm2java
 */
public class Organization  implements java.io.Serializable {


     private String orgname;
     private byte[] orglogo;
     private String imagename;
     private String orgdetails;
     private Integer noofbranches;
     private Set branches = new HashSet(0);

    public Organization() {
    }

	
    public Organization(String orgname) {
        this.orgname = orgname;
    }
    public Organization(String orgname, byte[] orglogo, String orgdetails, Integer noofbranches, Set branches,String imagename) {
       this.orgname = orgname;
       this.orglogo = orglogo;
       this.orgdetails = orgdetails;
       this.noofbranches = noofbranches;
       this.branches = branches;
       this.imagename=imagename;
    }
   
    public String getOrgname() {
        return this.orgname;
    }
    
    public void setOrgname(String orgname) {
        this.orgname = orgname;
    }

    public byte[] getOrglogo() {
        return orglogo;
    }

    public void setOrglogo(byte[] orglogo) {
        this.orglogo = orglogo;
    }

    public String getImagename() {
        return imagename;
    }

    public void setImagename(String imagename) {
        this.imagename = imagename;
    }
    
    
    public String getOrgdetails() {
        return this.orgdetails;
    }
    
    public void setOrgdetails(String orgdetails) {
        this.orgdetails = orgdetails;
    }
    public Integer getNoofbranches() {
        return this.noofbranches;
    }
    
    public void setNoofbranches(Integer noofbranches) {
        this.noofbranches = noofbranches;
    }
    public Set getBranches() {
        return this.branches;
    }
    
    public void setBranches(Set branches) {
        this.branches = branches;
    }




}


