package Prototypical;
// Generated 1 Feb, 2015 4:12:43 PM by Hibernate Tools 3.6.0


import java.util.Collection;
import java.util.HashSet;
import java.util.Set;

/**
 * Person generated by hbm2java
 */
public class Person  implements java.io.Serializable {


     private Integer personid;
     private String fname;
     private String mname;
     private String lname;
     private String emailid;
     private String street;
     private String city;
     private String state;
     private String country;
     private Integer pincode;
     private String username;
     private String password;
     private String confirmpassword;
     private Set contact = new HashSet(0);
     private Set languageknown = new HashSet(0);
     private String type;
     private Set<Workexperience> workexperience;
     private Set<Acdemicdetails> acdemicdetails=new HashSet();

    public Person() {
    }

	
    public Person(Integer personid) {
        this.personid = personid;
    }

    public Set getLanguageknown() {
        return languageknown;
    }

    public void setLanguageknown(Set languageknown) {
        this.languageknown = languageknown;
    }

   
    
    
    
    public Person(Integer personid, String fname, String mname, String lname, String emailid, String street, String city, String state, String country, Integer pincode, String username, String password, String confirmpassword, Set contact) {
       this.personid = personid;
       this.fname = fname;
       this.mname = mname;
       this.lname = lname;
       this.emailid = emailid;
       this.street = street;
       this.city = city;
       this.state = state;
       this.country = country;
       this.pincode = pincode;
       this.username = username;
       this.password = password;
       this.confirmpassword = confirmpassword;
       this.contact = contact;
       
    }
   
    public Integer getPersonid() {
        return this.personid;
    }
    
    public void setPersonid(Integer personid) {
        this.personid = personid;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getMname() {
        return this.mname;
    }
    
    public void setMname(String mname) {
        this.mname = mname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getEmailid() {
        return this.emailid;
    }
    
    public void setEmailid(String emailid) {
        this.emailid = emailid;
    }
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public Integer getPincode() {
        return this.pincode;
    }
    
    public void setPincode(Integer pincode) {
        this.pincode = pincode;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getConfirmpassword() {
        return this.confirmpassword;
    }
    
    public void setConfirmpassword(String confirmpassword) {
        this.confirmpassword = confirmpassword;
    }
    public Set getContact() {
        return this.contact;
    }
    
    public void setContact(Set contact) {
        this.contact = contact;
    }


    public Set<Acdemicdetails> getAcdemicdetails() {
        return acdemicdetails;
    }

    public void setAcdemicdetails(Set<Acdemicdetails> acdemicdetails) {
        this.acdemicdetails = acdemicdetails;
    }


    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Set<Workexperience> getWorkexperience() {
        return workexperience;
    }

    public void setWorkexperience(Set<Workexperience> workexperience) {
        this.workexperience = workexperience;
    }

   

   

  

  
}


