package Prototypical;
// Generated 1 Feb, 2015 4:12:43 PM by Hibernate Tools 3.6.0



/**
 * Requireddocuments generated by hbm2java
 */
public class Requireddocuments  implements java.io.Serializable {


     private RequireddocumentsId id;

    public Requireddocuments() {
    }

    public Requireddocuments(RequireddocumentsId id) {
       this.id = id;
    }
   
    public RequireddocumentsId getId() {
        return this.id;
    }
    
    public void setId(RequireddocumentsId id) {
        this.id = id;
    }




}


