package Prototypical;
// Generated 1 Feb, 2015 4:12:43 PM by Hibernate Tools 3.6.0



/**
 * Requiedqualification generated by hbm2java
 */
public class Requiedqualification  implements java.io.Serializable {


     private RequiedqualificationId id;
     private Jobopeningdetails jobopeningdetails;

    public Requiedqualification() {
    }

    public Requiedqualification(RequiedqualificationId id, Jobopeningdetails jobopeningdetails) {
       this.id = id;
       this.jobopeningdetails = jobopeningdetails;
    }
   
    public RequiedqualificationId getId() {
        return this.id;
    }
    
    public void setId(RequiedqualificationId id) {
        this.id = id;
    }
    public Jobopeningdetails getJobopeningdetails() {
        return this.jobopeningdetails;
    }
    
    public void setJobopeningdetails(Jobopeningdetails jobopeningdetails) {
        this.jobopeningdetails = jobopeningdetails;
    }

    @Override
    public String toString() {
        return "Requiedqualification{" + "id=" + id + ", jobopeningdetails=" + jobopeningdetails + '}';
    }




}


