package Prototypical;
// Generated 1 Feb, 2015 4:12:43 PM by Hibernate Tools 3.6.0



/**
 * RequireddocumentsId generated by hbm2java
 */
public class RequireddocumentsId  implements java.io.Serializable {


     private int jobReferenceCode;
     private String requiredDocuments;

    public RequireddocumentsId() {
    }

    public RequireddocumentsId(int jobReferenceCode, String requiredDocuments) {
       this.jobReferenceCode = jobReferenceCode;
       this.requiredDocuments = requiredDocuments;
    }
   
    public int getJobReferenceCode() {
        return this.jobReferenceCode;
    }
    
    public void setJobReferenceCode(int jobReferenceCode) {
        this.jobReferenceCode = jobReferenceCode;
    }
    public String getRequiredDocuments() {
        return this.requiredDocuments;
    }
    
    public void setRequiredDocuments(String requiredDocuments) {
        this.requiredDocuments = requiredDocuments;
    }




}


