package Prototypical;
// Generated 18 Feb, 2015 7:31:37 PM by Hibernate Tools 3.6.0



/**
 * ResultId generated by hbm2java
 */
public class ResultId  implements java.io.Serializable {


     private int personid;
     private int roundId;

    public ResultId() {
    }

    public int getPersonid() {
        return personid;
    }

    public void setPersonid(int personid) {
        this.personid = personid;
    }

    public ResultId(int personid, int roundId) {
        this.personid = personid;
        this.roundId = roundId;
    }

    public int getRoundId() {
        return this.roundId;
    }
    
    public void setRoundId(int roundId) {
        this.roundId = roundId;
    }

    @Override
    public String toString() {
        return "ResultId{" + "personid=" + personid + ", roundId=" + roundId + '}';
    }




}


