package Prototypical;
// Generated 18 Feb, 2015 4:33:01 PM by Hibernate Tools 3.6.0



/**
 * ScheduleId generated by hbm2java
 */
public class ScheduleId  implements java.io.Serializable {


     private int scheduleNo;
     private int roundId;

    public ScheduleId() {
    }

    public ScheduleId(int scheduleNo, int roundId) {
       this.scheduleNo = scheduleNo;
       this.roundId = roundId;
    }
   
    public int getScheduleNo() {
        return this.scheduleNo;
    }
    
    public void setScheduleNo(int scheduleNo) {
        this.scheduleNo = scheduleNo;
    }
    public int getRoundId() {
        return this.roundId;
    }
    
    public void setRoundId(int roundId) {
        this.roundId = roundId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ScheduleId) ) return false;
		 ScheduleId castOther = ( ScheduleId ) other; 
         
		 return (this.getScheduleNo()==castOther.getScheduleNo())
 && (this.getRoundId()==castOther.getRoundId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getScheduleNo();
         result = 37 * result + this.getRoundId();
         return result;
   }   

    @Override
    public String toString() {
        return "ScheduleId{" + "scheduleNo=" + scheduleNo + ", roundId=" + roundId + '}';
    }


}


