package Prototypical;
// Generated 27 Feb, 2015 4:15:24 PM by Hibernate Tools 3.6.0



/**
 * WorkexperienceId generated by hbm2java
 */
public class WorkexperienceId  implements java.io.Serializable {


     private Integer desiredid;
     private String orgname;
     private String responsibility;
     private String designation;
     private Float duration;
     private Float salaryDrawn;

    public WorkexperienceId() {
    }

    public WorkexperienceId(Integer desiredid, String orgname, String responsibility, String designation, Float duration, Float salaryDrawn) {
       this.desiredid = desiredid;
       this.orgname = orgname;
       this.responsibility = responsibility;
       this.designation = designation;
       this.duration = duration;
       this.salaryDrawn = salaryDrawn;
    }
   
    public Integer getDesiredid() {
        return this.desiredid;
    }
    
    public void setDesiredid(Integer desiredid) {
        this.desiredid = desiredid;
    }
    public String getOrgname() {
        return this.orgname;
    }
    
    public void setOrgname(String orgname) {
        this.orgname = orgname;
    }
    public String getResponsibility() {
        return this.responsibility;
    }
    
    public void setResponsibility(String responsibility) {
        this.responsibility = responsibility;
    }
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }
    public Float getDuration() {
        return this.duration;
    }
    
    public void setDuration(Float duration) {
        this.duration = duration;
    }
    public Float getSalaryDrawn() {
        return this.salaryDrawn;
    }
    
    public void setSalaryDrawn(Float salaryDrawn) {
        this.salaryDrawn = salaryDrawn;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof WorkexperienceId) ) return false;
		 WorkexperienceId castOther = ( WorkexperienceId ) other; 
         
		 return ( (this.getDesiredid()==castOther.getDesiredid()) || ( this.getDesiredid()!=null && castOther.getDesiredid()!=null && this.getDesiredid().equals(castOther.getDesiredid()) ) )
 && ( (this.getOrgname()==castOther.getOrgname()) || ( this.getOrgname()!=null && castOther.getOrgname()!=null && this.getOrgname().equals(castOther.getOrgname()) ) )
 && ( (this.getResponsibility()==castOther.getResponsibility()) || ( this.getResponsibility()!=null && castOther.getResponsibility()!=null && this.getResponsibility().equals(castOther.getResponsibility()) ) )
 && ( (this.getDesignation()==castOther.getDesignation()) || ( this.getDesignation()!=null && castOther.getDesignation()!=null && this.getDesignation().equals(castOther.getDesignation()) ) )
 && ( (this.getDuration()==castOther.getDuration()) || ( this.getDuration()!=null && castOther.getDuration()!=null && this.getDuration().equals(castOther.getDuration()) ) )
 && ( (this.getSalaryDrawn()==castOther.getSalaryDrawn()) || ( this.getSalaryDrawn()!=null && castOther.getSalaryDrawn()!=null && this.getSalaryDrawn().equals(castOther.getSalaryDrawn()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDesiredid() == null ? 0 : this.getDesiredid().hashCode() );
         result = 37 * result + ( getOrgname() == null ? 0 : this.getOrgname().hashCode() );
         result = 37 * result + ( getResponsibility() == null ? 0 : this.getResponsibility().hashCode() );
         result = 37 * result + ( getDesignation() == null ? 0 : this.getDesignation().hashCode() );
         result = 37 * result + ( getDuration() == null ? 0 : this.getDuration().hashCode() );
         result = 37 * result + ( getSalaryDrawn() == null ? 0 : this.getSalaryDrawn().hashCode() );
         return result;
   }   

    @Override
    public String toString() {
        return "WorkexperienceId{" + "desiredid=" + desiredid + ", orgname=" + orgname + ", responsibility=" + responsibility + ", designation=" + designation + ", duration=" + duration + ", salaryDrawn=" + salaryDrawn + '}';
    }


}


