package Prototypical;
// Generated 27 Feb, 2015 4:15:24 PM by Hibernate Tools 3.6.0



/**
 * Workexperience generated by hbm2java
 */
public class Workexperience  implements java.io.Serializable {


     private WorkexperienceId id;

    public Workexperience() {
    }

    public Workexperience(WorkexperienceId id) {
       this.id = id;
    }
   
    public WorkexperienceId getId() {
        return this.id;
    }
    
    public void setId(WorkexperienceId id) {
        this.id = id;
    }

    @Override
    public String toString() {
        return "Workexperience{" + "id=" + id + '}';
    }




}


